/**
 * HermesClaw-v2 完整 Mock 数据集
 * —— 外贸行业 MVP 阶段全量演示数据，字段完整、跨引用一致
 *
 * ⚠️ SEED ONLY — 仅供 prisma seed 与初始化脚本使用，**禁止**被任何 UI 组件、
 *   Route Handler 或服务端业务代码直接 import。UI 必须经由 prisma / API
 *   读取真实持久化数据。
 *
 * 跨实体引用关系：
 *   Agent.bindSkills       → Skill.id
 *   Agent.bindConnectors   → Connector.id
 *   Project.activeAgents   → Agent.id
 *   Memory.relatedProject  → Project.id
 *   Memory.relatedAgent    → Agent.id
 *   Connector.usedByAgents → Agent.id
 *   Skill.usedByAgents     → Agent.id
 *   Quotation.projectId    → Project.id
 */

import type {
  Agent,
  Project,
  Memory,
  Connector,
  Skill,
  HarnessProposal,
  Inquiry,
  MarketIntelligence,
  Quotation,
} from '@/types'

// ============================================================
// 技能 Skills（12 个）
// ============================================================
export const mockSkills: Skill[] = [
  {
    id: 'skill-001',
    name: '开发信写作',
    description: '根据客户画像与产品信息，自动生成多语种个性化开发信，支持 A/B 版本对比',
    version: '2.1.0',
    category: '外贸写作',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"productInfo":"object","clientProfile":"object","language":"string","tone":"string"}',
    outputSchema: '{"subject":"string","body":"string","abVersion":"string","confidence":"number"}',
    usedByAgents: ['agent-001', 'agent-007'],
    scenarios: ['新客户触达', '展会后续跟进', '沉睡客户激活'],
    automationLevel: 'L2',
    updatedAt: '2026-05-20T10:30:00Z',
  },
  {
    id: 'skill-002',
    name: '询盘分析',
    description: '对入站询盘进行意图识别、优先级评分、虚假询盘过滤，输出结构化分析报告',
    version: '1.8.3',
    category: '外贸分析',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"inquiryText":"string","senderInfo":"object","channel":"string"}',
    outputSchema: '{"intent":"string","priority":"string","genuineScore":"number","recommendedReply":"string"}',
    usedByAgents: ['agent-002', 'agent-007'],
    scenarios: ['询盘初筛', 'B2B 平台询盘处理', '邮件询盘分类'],
    automationLevel: 'L2',
    updatedAt: '2026-06-01T08:15:00Z',
  },
  {
    id: 'skill-003',
    name: '报价生成',
    description: '基于产品配置、汇率、关税、运费自动生成多币种报价单，支持版本管理',
    version: '3.0.1',
    category: '外贸商务',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"productConfig":"object","currency":"string","incoterms":"string","quantity":"number"}',
    outputSchema: '{"unitPrice":"number","totalAmount":"number","validityDays":"number","termsText":"string"}',
    usedByAgents: ['agent-004'],
    scenarios: ['FOB 报价', 'CIF 报价', '阶梯报价', '样品报价'],
    automationLevel: 'L2',
    updatedAt: '2026-05-28T14:00:00Z',
  },
  {
    id: 'skill-004',
    name: '客户画像构建',
    description: '从邮件、聊天记录、交易历史中提取客户特征，构建 360° 客户画像',
    version: '2.3.0',
    category: '外贸分析',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"contactInfo":"object","history":"array","channels":"array"}',
    outputSchema: '{"profile":"object","persona":"string","buyingSignals":"array","riskFlags":"array"}',
    usedByAgents: ['agent-003', 'agent-007'],
    scenarios: ['新客户建档', '老客户画像更新', '流失预警'],
    automationLevel: 'L2',
    updatedAt: '2026-04-15T09:00:00Z',
  },
  {
    id: 'skill-005',
    name: '邮件分类与路由',
    description: '自动分类入站邮件（询盘/订单/投诉/垃圾），按规则路由到对应智能体处理',
    version: '1.5.2',
    category: '外贸自动化',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"email":"object","rules":"array"}',
    outputSchema: '{"category":"string","sentiment":"string","assignedAgent":"string","priority":"string"}',
    usedByAgents: ['agent-010'],
    scenarios: ['日常邮件分拣', '大促期间邮件洪峰', '多语种邮件路由'],
    automationLevel: 'L2',
    updatedAt: '2026-05-10T16:45:00Z',
  },
  {
    id: 'skill-006',
    name: '市场调研报告',
    description: '自动采集行业数据、竞品信息、海关数据，生成结构化市场调研报告',
    version: '1.2.0',
    category: '外贸分析',
    source: 'EXTERNAL',
    status: 'active',
    inputSchema: '{"market":"string","competitors":"array","dateRange":"object","dataSources":"array"}',
    outputSchema: '{"report":"string","keyFindings":"array","charts":"array","recommendations":"array"}',
    usedByAgents: ['agent-006'],
    scenarios: ['新市场进入评估', '季度市场复盘', '竞品动态监控'],
    automationLevel: 'L2',
    updatedAt: '2026-03-22T11:00:00Z',
  },
  {
    id: 'skill-007',
    name: '合同条款审查',
    description: '审查外贸合同中的风险条款、不一致项、缺失项，输出风险标注版',
    version: '1.0.5',
    category: '外贸合规',
    source: 'EXTERNAL',
    status: 'active',
    inputSchema: '{"contractText":"string","template":"string","jurisdiction":"string"}',
    outputSchema: '{"riskItems":"array","missingClauses":"array","overallScore":"number"}',
    usedByAgents: ['agent-008'],
    scenarios: ['销售合同审查', '采购合同审查', '代理协议审查'],
    automationLevel: 'L2',
    updatedAt: '2026-02-18T13:30:00Z',
  },
  {
    id: 'skill-008',
    name: '多语种翻译',
    description: '支持 12 种外贸常用语言的精准翻译，保留行业术语与品牌调性',
    version: '4.1.0',
    category: '外贸工具',
    source: 'BUILTIN',
    status: 'active',
    inputSchema: '{"sourceText":"string","sourceLang":"string","targetLang":"string","domain":"string"}',
    outputSchema: '{"translated":"string","confidence":"number","termMapping":"object"}',
    usedByAgents: ['agent-001', 'agent-004', 'agent-007'],
    scenarios: ['产品描述翻译', '邮件翻译', '合同双语对照'],
    automationLevel: 'L2',
    updatedAt: '2026-05-05T07:00:00Z',
  },
  {
    id: 'skill-009',
    name: '产品描述生成',
    description: '根据产品参数批量生成电商平台、B2B 平台、独立站风格的产品描述',
    version: '2.0.0',
    category: '外贸写作',
    source: 'CUSTOM',
    status: 'active',
    inputSchema: '{"productParams":"object","platform":"string","targetAudience":"string"}',
    outputSchema: '{"title":"string","description":"string","bulletPoints":"array","keywords":"array"}',
    usedByAgents: ['agent-005'],
    scenarios: ['阿里巴巴产品发布', '亚马逊 Listing', '独立站产品页'],
    automationLevel: 'L2',
    updatedAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'skill-010',
    name: '展会线索整理',
    description: '将展会名片、聊天记录、备注照片结构化整理，输出可跟进的线索列表',
    version: '1.3.2',
    category: '外贸自动化',
    source: 'CUSTOM',
    status: 'active',
    inputSchema: '{"rawInputs":"array","exhibitionName":"string","date":"string"}',
    outputSchema: '{"leads":"array","hotLeads":"array","followUpSchedule":"array","summary":"string"}',
    usedByAgents: ['agent-009'],
    scenarios: ['广交会线索整理', '海外展会跟进', '线上展会线索提取'],
    automationLevel: 'L2',
    updatedAt: '2026-05-12T15:20:00Z',
  },
  {
    id: 'skill-011',
    name: '物流追踪与预警',
    description: '接入物流 API 实时追踪货运状态，异常自动预警并提供替代方案建议',
    version: '1.1.0',
    category: '外贸运营',
    source: 'EXTERNAL',
    status: 'active',
    inputSchema: '{"trackingNumbers":"array","carriers":"array","expectedETA":"string"}',
    outputSchema: '{"status":"array","anomalies":"array","suggestions":"array","onTimeRate":"number"}',
    usedByAgents: ['agent-003'],
    scenarios: ['海运追踪', '空运追踪', '多式联运监控'],
    automationLevel: 'L2',
    updatedAt: '2026-06-03T09:45:00Z',
  },
  {
    id: 'skill-012',
    name: '竞品价格监控',
    description: '自动抓取竞品定价、促销活动、新品发布信息，生成价格波动预警',
    version: '1.0.2',
    category: '外贸分析',
    source: 'CUSTOM',
    status: 'active',
    inputSchema: '{"competitors":"array","products":"array","platforms":"array","frequency":"string"}',
    outputSchema: '{"priceChanges":"array","promotions":"array","trendAnalysis":"string"}',
    usedByAgents: ['agent-006'],
    scenarios: ['竞品定价跟踪', '促销季价格策略', '新品市场定价参考'],
    automationLevel: 'L2',
    updatedAt: '2026-05-30T12:00:00Z',
  },
]

// ============================================================
// 连接器 Connectors（20 个）
// ============================================================
export const mockConnectors: Connector[] = [
  // ---- Email 类 ----
  {
    id: 'conn-001',
    name: 'Gmail',
    iconEmoji: '📧',
    description: 'Google Workspace 邮箱连接器，支持收发邮件、标签管理、附件解析',
    status: 'connected',
    category: 'email',
    lastSync: '2026-06-06T08:30:00Z',
    permissions: ['read', 'send', 'labels', 'attachments'],
    usedByAgents: ['agent-001', 'agent-002', 'agent-003', 'agent-010'],
  },
  {
    id: 'conn-002',
    name: 'Outlook',
    iconEmoji: '📨',
    description: 'Microsoft 365 邮箱连接器，支持邮件、日历、联系人同步',
    status: 'connected',
    category: 'email',
    lastSync: '2026-06-06T09:00:00Z',
    permissions: ['read', 'send', 'calendar', 'contacts'],
    usedByAgents: ['agent-004', 'agent-007'],
  },
  {
    id: 'conn-003',
    name: '阿里企业邮箱',
    iconEmoji: '📬',
    description: '阿里巴巴企业邮箱连接器，适用于国内外贸企业常用邮箱体系',
    status: 'available',
    category: 'email',
    permissions: ['read', 'send'],
    usedByAgents: [],
  },
  {
    id: 'conn-004',
    name: '网易企业邮',
    iconEmoji: '✉️',
    description: '网易企业邮箱连接器，国内外贸公司高频使用',
    status: 'connected',
    category: 'email',
    lastSync: '2026-06-05T17:45:00Z',
    permissions: ['read', 'send', 'attachments'],
    usedByAgents: ['agent-002', 'agent-005'],
  },
  // ---- IM 类 ----
  {
    id: 'conn-005',
    name: 'WhatsApp Business',
    iconEmoji: '💬',
    description: 'WhatsApp Business API 连接器，支持消息收发、模板消息、多媒体',
    status: 'connected',
    category: 'im',
    lastSync: '2026-06-06T10:15:00Z',
    permissions: ['read', 'send', 'templates', 'media'],
    usedByAgents: ['agent-003', 'agent-007'],
  },
  {
    id: 'conn-006',
    name: 'Slack',
    iconEmoji: '💼',
    description: 'Slack 工作空间连接器，支持频道消息、文件共享、通知推送',
    status: 'available',
    category: 'im',
    permissions: ['read', 'write', 'files', 'channels'],
    usedByAgents: [],
  },
  {
    id: 'conn-007',
    name: '微信企业版',
    iconEmoji: '💚',
    description: '企业微信连接器，支持客户群消息、内部协作、审批通知',
    status: 'connected',
    category: 'im',
    lastSync: '2026-06-06T07:30:00Z',
    permissions: ['read', 'send', 'groups', 'moments'],
    usedByAgents: ['agent-003', 'agent-007'],
  },
  // ---- CRM 类 ----
  {
    id: 'conn-008',
    name: 'HubSpot',
    iconEmoji: '🔶',
    description: 'HubSpot CRM 连接器，同步客户、交易、任务、邮件营销数据',
    status: 'connected',
    category: 'crm',
    lastSync: '2026-06-06T09:30:00Z',
    permissions: ['contacts', 'deals', 'tasks', 'emails'],
    usedByAgents: ['agent-003', 'agent-004', 'agent-007'],
  },
  {
    id: 'conn-009',
    name: 'Salesforce',
    iconEmoji: '☁️',
    description: 'Salesforce CRM 连接器，适用于中大型外贸企业的客户关系管理',
    status: 'available',
    category: 'crm',
    permissions: ['accounts', 'opportunities', 'leads', 'reports'],
    usedByAgents: [],
  },
  {
    id: 'conn-010',
    name: 'Zoho CRM',
    iconEmoji: '📋',
    description: 'Zoho CRM 连接器，适用于中小企业外贸客户管理与销售自动化',
    status: 'connected',
    category: 'crm',
    lastSync: '2026-06-06T08:00:00Z',
    permissions: ['contacts', 'deals', 'activities', 'notes'],
    usedByAgents: ['agent-004', 'agent-006'],
  },
  // ---- ERP 类 ----
  {
    id: 'conn-011',
    name: 'SAP Business One',
    iconEmoji: '🏭',
    description: 'SAP B1 ERP 连接器，同步订单、库存、财务、采购数据',
    status: 'available',
    category: 'erp',
    permissions: ['orders', 'inventory', 'finance', 'purchasing'],
    usedByAgents: [],
  },
  {
    id: 'conn-012',
    name: '用友 U8',
    iconEmoji: '📊',
    description: '用友 U8 ERP 连接器，国内外贸工厂常用，同步生产、库存、财务',
    status: 'connecting',
    category: 'erp',
    permissions: ['orders', 'inventory', 'production', 'finance'],
    usedByAgents: [],
  },
  // ---- Document 类 ----
  {
    id: 'conn-013',
    name: 'Notion',
    iconEmoji: '📝',
    description: 'Notion 工作空间连接器，同步知识库、项目文档、会议记录',
    status: 'connected',
    category: 'document',
    lastSync: '2026-06-06T06:00:00Z',
    permissions: ['read', 'write', 'databases', 'pages'],
    usedByAgents: ['agent-005', 'agent-006'],
  },
  {
    id: 'conn-014',
    name: 'Google Drive',
    iconEmoji: '📁',
    description: 'Google Drive 云盘连接器，支持文件存取、OCR、电子表格解析',
    status: 'connected',
    category: 'document',
    lastSync: '2026-06-05T22:00:00Z',
    permissions: ['read', 'write', 'sheets', 'docs'],
    usedByAgents: ['agent-001', 'agent-005'],
  },
  {
    id: 'conn-015',
    name: '飞书文档',
    iconEmoji: '🐦',
    description: '飞书文档连接器，支持多维表格、文档协同、审批单',
    status: 'error',
    category: 'document',
    lastSync: '2026-06-04T15:30:00Z',
    permissions: ['read', 'write', 'sheets', 'docs'],
    usedByAgents: ['agent-005'],
  },
  // ---- Data 类 ----
  {
    id: 'conn-016',
    name: '海关数据平台',
    iconEmoji: '🏷️',
    description: '海关进出口数据连接器，支持 HS 编码查询、贸易流向、量价分析',
    status: 'connected',
    category: 'data',
    lastSync: '2026-06-06T04:00:00Z',
    permissions: ['query', 'export'],
    usedByAgents: ['agent-006'],
  },
  {
    id: 'conn-017',
    name: '阿里巴巴国际站',
    iconEmoji: '🌐',
    description: 'Alibaba.com 平台连接器，同步产品、询盘、RFQ、交易数据',
    status: 'connected',
    category: 'data',
    lastSync: '2026-06-06T08:45:00Z',
    permissions: ['products', 'inquiries', 'rfq', 'orders'],
    usedByAgents: ['agent-002', 'agent-007'],
  },
  {
    id: 'conn-018',
    name: '汇率 API (XE)',
    iconEmoji: '💱',
    description: '实时汇率数据连接器，支持 170+ 货币对、历史汇率、波动预警',
    status: 'connected',
    category: 'data',
    lastSync: '2026-06-06T10:00:00Z',
    permissions: ['rates', 'history', 'alerts'],
    usedByAgents: ['agent-004', 'agent-006'],
  },
  // ---- API 类 ----
  {
    id: 'conn-019',
    name: 'Shopify',
    iconEmoji: '🛒',
    description: 'Shopify 电商平台连接器，同步订单、产品、客户、物流信息',
    status: 'connected',
    category: 'api',
    lastSync: '2026-06-06T09:15:00Z',
    permissions: ['orders', 'products', 'customers', 'fulfillment'],
    usedByAgents: ['agent-004', 'agent-007'],
  },
  {
    id: 'conn-020',
    name: 'Stripe',
    iconEmoji: '💳',
    description: 'Stripe 支付连接器，支持收付款、发票、订阅管理、多币种结算',
    status: 'available',
    category: 'api',
    permissions: ['payments', 'invoices', 'subscriptions', 'reports'],
    usedByAgents: [],
  },
]

// ============================================================
// 智能体 Agents（10 个）
// ============================================================
export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Leon',
    role: '开发信写手',
    description: '专精多语种开发信写作与 A/B 测试，根据客户画像和产品特性自动生成高转化率触达邮件',
    status: 'running',
    source: 'BUILTIN',
    category: ['外贸写作', '客户触达'],
    bindSkills: ['skill-001', 'skill-008'],
    bindConnectors: ['conn-001', 'conn-014'],
    memoryPermission: 'read-write',
    harnessVersion: '2.1.3',
    automationLevel: 'L2',
    canDo: ['撰写多语种开发信', 'A/B 版本对比测试', '调用客户画像数据', '记录触达结果到中期记忆'],
    cannotDo: ['直接发送未经人工审核的邮件', '修改客户核心数据', '调用支付相关连接器'],
    stats: { todayTasks: 23, successRate: 0.94, avgDuration: '2m 18s' },
    lastActive: '2026-06-06T10:32:00Z',
    createdAt: '2025-11-15T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-email-writer',
  },
  {
    id: 'agent-002',
    name: 'Clara',
    role: '询盘分拣员',
    description: '自动分拣入站询盘，识别虚假询盘与高价值询盘，按优先级路由到对应销售或跟进流程',
    status: 'running',
    source: 'BUILTIN',
    category: ['外贸分析', '询盘管理'],
    bindSkills: ['skill-002', 'skill-005'],
    bindConnectors: ['conn-001', 'conn-004', 'conn-017'],
    memoryPermission: 'read-write',
    harnessVersion: '2.0.1',
    automationLevel: 'L1',
    canDo: ['分析入站询盘意图', '评分与优先级排序', '检测虚假询盘模式', '自动分配至对应销售'],
    cannotDo: ['直接回复客户', '修改报价数据', '访问 ERP 财务模块'],
    stats: { todayTasks: 47, successRate: 0.91, avgDuration: '45s' },
    lastActive: '2026-06-06T10:45:00Z',
    createdAt: '2025-12-01T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-inquiry-sorter',
  },
  {
    id: 'agent-003',
    name: 'Marcus',
    role: '客户跟进员',
    description: '管理客户跟进节奏，根据阶段自动生成跟进内容，预警客户流失并推荐挽回策略',
    status: 'idle',
    source: 'BUILTIN',
    category: ['客户管理', '销售跟进'],
    bindSkills: ['skill-004', 'skill-011'],
    bindConnectors: ['conn-001', 'conn-005', 'conn-007', 'conn-008'],
    memoryPermission: 'read-write',
    harnessVersion: '2.0.5',
    automationLevel: 'L2',
    canDo: ['管理客户跟进周期', '生成个性化跟进内容', '客户流失预警', '同步跟进记录至 CRM'],
    cannotDo: ['修改合同条款', '自行决定报价折扣', '删除客户记录'],
    stats: { todayTasks: 18, successRate: 0.88, avgDuration: '3m 05s' },
    lastActive: '2026-06-06T09:58:00Z',
    createdAt: '2026-01-10T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-followup-manager',
  },
  {
    id: 'agent-004',
    name: 'Quincy',
    role: '报价代理',
    description: '基于实时汇率、原材料成本、运费、关税自动计算并生成多币种专业报价单',
    status: 'running',
    source: 'BUILTIN',
    category: ['外贸商务', '定价管理'],
    bindSkills: ['skill-003', 'skill-008'],
    bindConnectors: ['conn-002', 'conn-008', 'conn-010', 'conn-018', 'conn-019'],
    memoryPermission: 'read-write',
    harnessVersion: '2.2.0',
    automationLevel: 'L3',
    canDo: ['多币种报价计算', '阶梯数量报价', '报价版本管理', '调用实时汇率与运费数据'],
    cannotDo: ['绕过审批直接发送报价', '修改底价策略', '自行决定付款条款'],
    stats: { todayTasks: 12, successRate: 0.96, avgDuration: '4m 30s' },
    lastActive: '2026-06-06T10:15:00Z',
    createdAt: '2026-02-05T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-quotation-specialist',
  },
  {
    id: 'agent-005',
    name: 'Diana',
    role: '产品资料员',
    description: '管理和生成产品资料，将产品参数转化为多渠道适配的产品描述、规格书与目录',
    status: 'idle',
    source: 'BUILTIN',
    category: ['产品管理', '内容生产'],
    bindSkills: ['skill-009'],
    bindConnectors: ['conn-004', 'conn-013', 'conn-014', 'conn-015'],
    memoryPermission: 'read',
    harnessVersion: '2.0.2',
    automationLevel: 'L2',
    canDo: ['生成多平台产品描述', '产品资料版本管理', '从技术文档提取产品参数', '管理产品图片与附件'],
    cannotDo: ['修改产品定价', '发布至未经审核的平台', '删除已归档产品资料'],
    stats: { todayTasks: 8, successRate: 0.92, avgDuration: '5m 12s' },
    lastActive: '2026-06-05T18:30:00Z',
    createdAt: '2026-01-22T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-product-manager',
  },
  {
    id: 'agent-006',
    name: 'Athena',
    role: '市场研究员',
    description: '持续监测行业趋势、竞品动作、政策变化，输出市场周报和机会洞察',
    status: 'running',
    source: 'BUILTIN',
    category: ['市场研究', '商业情报'],
    bindSkills: ['skill-006', 'skill-012'],
    bindConnectors: ['conn-010', 'conn-013', 'conn-016', 'conn-018'],
    memoryPermission: 'read-write',
    harnessVersion: '2.1.0',
    automationLevel: 'L1',
    canDo: ['采集行业与竞品数据', '生成市场周报/月报', '识别市场机会与风险', '生成情报分发建议'],
    cannotDo: ['执行交易操作', '修改客户数据', '对外发布未经审阅的情报'],
    stats: { todayTasks: 5, successRate: 0.95, avgDuration: '12m 40s' },
    lastActive: '2026-06-06T09:00:00Z',
    createdAt: '2026-03-01T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-market-researcher',
  },
  {
    id: 'agent-007',
    name: 'Sophia',
    role: '外贸销售助手',
    description: '全流程销售辅助：从线索激活、需求沟通、样品跟进到订单促成，一站式赋能外贸业务员',
    status: 'running',
    source: 'BUILTIN',
    category: ['外贸销售', '全流程'],
    bindSkills: ['skill-001', 'skill-002', 'skill-004', 'skill-008'],
    bindConnectors: ['conn-002', 'conn-005', 'conn-007', 'conn-008', 'conn-017', 'conn-019'],
    memoryPermission: 'read-write',
    harnessVersion: '2.3.1',
    automationLevel: 'L2',
    canDo: ['全流程销售辅助', '协调各专项智能体', '汇总客户全渠道互动记录', '销售预测与建议'],
    cannotDo: ['直接签署合同', '单独决定大额折扣', '绕过合规审查流程'],
    stats: { todayTasks: 31, successRate: 0.89, avgDuration: '5m 50s' },
    lastActive: '2026-06-06T10:50:00Z',
    createdAt: '2025-12-20T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-sales-assistant',
  },
  {
    id: 'agent-008',
    name: 'Victor',
    role: '风险审查员',
    description: '审查客户信用、合同条款、支付风险与贸易合规性，为每一笔交易出具风险评估报告',
    status: 'idle',
    source: 'BUILTIN',
    category: ['合规风控', '外贸法务'],
    bindSkills: ['skill-007'],
    bindConnectors: ['conn-016'],
    memoryPermission: 'read',
    harnessVersion: '1.9.2',
    automationLevel: 'L3',
    canDo: ['审查合同风险条款', '评估客户信用风险', '检查贸易合规性', '出具风险报告供审批'],
    cannotDo: ['自行决定通过/驳回交易', '修改合同条款', '绕过法务审批流程'],
    stats: { todayTasks: 3, successRate: 0.97, avgDuration: '18m 20s' },
    lastActive: '2026-06-05T16:00:00Z',
    createdAt: '2026-02-15T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-risk-auditor',
  },
  {
    id: 'agent-009',
    name: 'Scout',
    role: '展会线索整理员',
    description: '将展会期间收集的名片、聊天截图、语音备忘等碎片化信息，整理为结构化可跟进线索',
    status: 'paused',
    source: 'industry',
    category: ['外贸展会', '线索管理'],
    bindSkills: ['skill-010'],
    bindConnectors: ['conn-008', 'conn-013'],
    memoryPermission: 'read-write',
    harnessVersion: '1.5.0',
    automationLevel: 'L1',
    canDo: ['整理展会碎片化信息', '线索结构化与评分', '生成跟进计划', '关联已有客户画像'],
    cannotDo: ['自行联系客户', '修改客户主数据', '外发展会报告'],
    stats: { todayTasks: 0, successRate: 0.86, avgDuration: '8m 00s' },
    lastActive: '2026-05-20T14:00:00Z',
    createdAt: '2026-04-01T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-exhibition-sorter',
  },
  {
    id: 'agent-010',
    name: 'Iris',
    role: '邮件分类员',
    description: '智能分类企业入站邮件，按业务类型自动打标、路由、归档，确保重要邮件零遗漏',
    status: 'running',
    source: 'BUILTIN',
    category: ['外贸自动化', '邮件管理'],
    bindSkills: ['skill-005'],
    bindConnectors: ['conn-001'],
    memoryPermission: 'read-write',
    harnessVersion: '1.8.0',
    automationLevel: 'L1',
    canDo: ['自动分类入站邮件', '按规则路由至对应处理人/Agent', '垃圾邮件过滤', '生成邮件处理报表'],
    cannotDo: ['阅读标记为私密的邮件', '删除邮件', '修改邮件规则（需审批）'],
    stats: { todayTasks: 156, successRate: 0.98, avgDuration: '8s' },
    lastActive: '2026-06-06T10:52:00Z',
    createdAt: '2025-12-10T08:00:00Z',
    industryId: 'foreign-trade',
    templateId: 'ft-email-classifier',
  },
]

// ============================================================
// 项目空间 Projects（8 个）
// ============================================================
export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: '美国 BrightPath 户外灯具订单',
    type: 'customer',
    status: 'active',
    owner: '张伟',
    relatedClient: 'BrightPath Outdoors Inc.',
    country: '美国',
    productLine: '户外LED灯具',
    activeAgents: ['agent-001', 'agent-004', 'agent-007'],
    riskPoints: ['客户对 UL 认证要求近期更新', '海运舱位紧张可能延迟'],
    nextActions: ['发送修订版报价单', '确认 UL 认证更新进展', '预订 7 月海运舱位'],
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-06-05T16:30:00Z',
    tags: ['重点客户', '灯具', '北美市场'],
  },
  {
    id: 'proj-002',
    name: '德国 Schmidt 精密五金长期合作',
    type: 'customer',
    status: 'active',
    owner: '李敏',
    relatedClient: 'Schmidt Präzisionstechnik GmbH',
    country: '德国',
    productLine: '精密五金件',
    activeAgents: ['agent-003', 'agent-004', 'agent-008'],
    riskPoints: ['REACH 法规更新需重新合规审查', '欧元汇率波动较大'],
    nextActions: ['更新 REACH 合规文档', '发送 Q3 价格调整通知', '安排技术视频会议'],
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-06-04T14:00:00Z',
    tags: ['战略合作', '五金', '欧洲市场', '长期客户'],
  },
  {
    id: 'proj-003',
    name: '日本 Sakura 家居收纳新品开发',
    type: 'customer',
    status: 'at-risk',
    owner: '王芳',
    relatedClient: '株式会社 Sakura Living',
    country: '日本',
    productLine: '家居收纳用品',
    activeAgents: ['agent-002', 'agent-005', 'agent-007'],
    riskPoints: ['样品第三次修改仍未通过日方质检', '竞品已抢先推出类似产品', '模具修改费用超预算 30%'],
    nextActions: ['紧急召开品控会议', '与客户协商交付时间调整', '评估模具方案替代供应商'],
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-06-06T09:15:00Z',
    tags: ['新品开发', '家居', '日本市场', '风险项目'],
  },
  {
    id: 'proj-004',
    name: '广交会春季 2026 线索跟进',
    type: 'exhibition',
    status: 'active',
    owner: '陈强',
    country: '中国',
    activeAgents: ['agent-002', 'agent-009', 'agent-010'],
    riskPoints: ['热线索超过 200 条需及时分发', '部分名片信息模糊需二次确认'],
    nextActions: ['按区域分配线索至销售', '发送标准化跟进模板', '标记高意向买家重点跟进'],
    createdAt: '2026-04-20T08:00:00Z',
    updatedAt: '2026-06-03T11:00:00Z',
    tags: ['展会', '广交会', '线索管理', '2026春季'],
  },
  {
    id: 'proj-005',
    name: '智能家居产品线 2026 出海计划',
    type: 'product-line',
    status: 'active',
    owner: '赵磊',
    productLine: '智能家居套件',
    country: '多国',
    activeAgents: ['agent-005', 'agent-006', 'agent-008'],
    riskPoints: ['目标市场认证（CE/FCC）尚未取得', '竞品在亚马逊已有较强品牌认知'],
    nextActions: ['完成 CE 认证测试', '制定亚马逊上线策略', '准备多语种产品内容'],
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-06-05T10:30:00Z',
    tags: ['产品线', '智能家居', '出海战略', '亚马逊'],
  },
  {
    id: 'proj-006',
    name: '英国 Hackett 百货 PO-2026-0421',
    type: 'order',
    status: 'active',
    owner: '刘洋',
    relatedClient: 'Hackett Department Stores Ltd.',
    country: '英国',
    productLine: '陶瓷餐具套装',
    activeAgents: ['agent-004', 'agent-007', 'agent-011'],
    riskPoints: ['英国脱欧后清关流程有变更', 'PO 交货期较紧仅剩 45 天'],
    nextActions: ['确认 UKCA 标识要求', '安排生产排期', '预订中欧班列仓位'],
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-06-06T08:45:00Z',
    tags: ['订单', '英国', '陶瓷', '紧急'],
  },
  {
    id: 'proj-007',
    name: '户外运动装备产品线拓展',
    type: 'product-line',
    status: 'paused',
    owner: '赵磊',
    productLine: '户外运动装备',
    country: '多国',
    activeAgents: ['agent-006'],
    riskPoints: ['原材料供应商更换中', '澳洲市场准入标准待确认'],
    nextActions: ['确认新供应商资质', '调研澳洲 AS/NZS 标准', '恢复市场调研任务'],
    createdAt: '2026-04-05T08:00:00Z',
    updatedAt: '2026-05-25T15:00:00Z',
    tags: ['产品线', '户外装备', '暂停'],
  },
  {
    id: 'proj-008',
    name: '东南亚家居市场代理拓展',
    type: 'customer',
    status: 'active',
    owner: '李敏',
    country: '多国',
    productLine: '整体家居解决方案',
    activeAgents: ['agent-006', 'agent-007'],
    riskPoints: ['印尼进口配额政策不明朗', '越南代理资质审查进行中'],
    nextActions: ['联系印尼当地律所确认配额政策', '完成越南代理背景调查', '准备代理商培训材料'],
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-06-02T13:30:00Z',
    tags: ['代理拓展', '家居', '东南亚'],
  },
]

// ============================================================
// 记忆 Memories（12 条：short 4 / mid 4 / long 4）
// ============================================================
export const mockMemories: Memory[] = [
  // ---- 短期记忆（short） ----
  {
    id: 'mem-001',
    type: 'short',
    content: 'BrightPath 客户在 2026-06-05 邮件中提到 UL 认证标准近期有更新，需要确认新款 IP65 灯具是否已满足最新要求。报价单需在 6 月 10 日前发出。',
    summary: 'BrightPath UL 认证更新提醒',
    source: 'Gmail 邮件解析',
    relatedProject: 'proj-001',
    relatedAgent: 'agent-004',
    confidence: 0.92,
    frozen: false,
    tags: ['认证', '报价', '紧迫'],
    createdAt: '2026-06-05T16:30:00Z',
  },
  {
    id: 'mem-002',
    type: 'short',
    content: '日本 Sakura 客户今日（6/6）通过 WhatsApp 告知，第三次样品外观仍有划痕问题，需要在 6 月 12 日前给出解决方案，否则可能转向备选供应商。',
    summary: 'Sakura 样品问题紧急反馈',
    source: 'WhatsApp 消息解析',
    relatedProject: 'proj-003',
    relatedAgent: 'agent-007',
    confidence: 0.95,
    frozen: false,
    tags: ['样品', '质量', '危机', '日本客户'],
    createdAt: '2026-06-06T09:15:00Z',
  },
  {
    id: 'mem-003',
    type: 'short',
    content: '今日广交会线索分配进度：已分配 120/200 条，尚有 80 条待处理。高意向买家集中在欧洲区（德国 12、法国 8、英国 6），需优先跟进。',
    summary: '广交会线索分配进度 60%',
    source: '系统任务面板',
    relatedProject: 'proj-004',
    relatedAgent: 'agent-009',
    confidence: 1.0,
    frozen: false,
    tags: ['展会', '线索', '跟进'],
    createdAt: '2026-06-06T09:00:00Z',
  },
  {
    id: 'mem-004',
    type: 'short',
    content: 'Clara（询盘分拣员）今日上午识别出 3 条疑似虚假询盘，来自尼日利亚和加纳 IP，模式特征：要求免费样品 + 提供模糊公司信息。已标记待人工复核。',
    summary: '今日虚假询盘预警',
    source: 'agent-002 运行日志',
    relatedAgent: 'agent-002',
    confidence: 0.78,
    frozen: false,
    tags: ['虚假询盘', '风控', '非洲'],
    createdAt: '2026-06-06T10:30:00Z',
  },
  // ---- 中期记忆（mid） ----
  {
    id: 'mem-005',
    type: 'mid',
    content: '与德国 Schmidt 客户的合作历史：自 2025 年 9 月起持续供货精密五金件，累计订单 8 笔，总金额 €320K。客户对质量要求极高，曾两次因表面处理色差退货，后续改用了指定的日本表面处理供应商后问题已解决。付款记录良好，平均回款周期 45 天。',
    summary: 'Schmidt 客户合作历史与质量要求',
    source: 'CRM + 订单系统汇总',
    relatedProject: 'proj-002',
    relatedAgent: 'agent-003',
    confidence: 0.98,
    frozen: true,
    tags: ['客户画像', '德国', '五金', '长期合作'],
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'mem-006',
    type: 'mid',
    content: '2026 年春季广交会总结：共收集 320 条线索，其中欧洲 45%、南美 25%、东南亚 20%、其他 10%。热门产品：智能家居、户外灯具、环保包装。客户关注点集中在：交期保障、认证齐全、MOQ 灵活度。已转化确认订单 8 笔，进入报价阶段 35 笔。',
    summary: '2026 春季广交会线索总结',
    source: '展会数据汇总',
    relatedProject: 'proj-004',
    relatedAgent: 'agent-009',
    confidence: 0.96,
    frozen: false,
    tags: ['展会', '广交会', '线索', '总结'],
    createdAt: '2026-05-10T08:00:00Z',
  },
  {
    id: 'mem-007',
    type: 'mid',
    content: '智能家居产品线出海策略已验证方向：欧美市场偏好能源管理类智能产品（智能插座、智能温控），东南亚市场偏好性价比高的智能安防套件。竞争对手 Aqara 在欧洲已建立较强渠道，建议差异化切入照明控制细分领域。',
    summary: '智能家居出海市场策略',
    source: 'agent-006 市场调研报告',
    relatedProject: 'proj-005',
    relatedAgent: 'agent-006',
    confidence: 0.85,
    frozen: false,
    tags: ['策略', '智能家居', '市场分析'],
    createdAt: '2026-05-25T14:00:00Z',
  },
  {
    id: 'mem-008',
    type: 'mid',
    content: '与日本 Sakura 客户的合作遇到反复质量挑战：自 2026 年 1 月以来已打样 3 次，均因外观瑕疵被拒。日方质检标准远高于欧美客户，建议建立专门的日本品质线。目前关系处于紧张状态，客户已提及备选供应商。',
    summary: 'Sakura 项目质量挑战记录',
    source: '项目日志聚合',
    relatedProject: 'proj-003',
    relatedAgent: 'agent-007',
    confidence: 0.93,
    frozen: false,
    tags: ['质量', '日本', '客户关系', '风险'],
    createdAt: '2026-06-01T10:00:00Z',
  },
  // ---- 长期记忆（long） ----
  {
    id: 'mem-009',
    type: 'long',
    content: '公司核心产品线知识库：户外 LED 灯具（IP65/IP67 等级，UL/CE/ROHS 认证，核心客户北美与欧洲）、精密五金件（CNC 加工，公差 ±0.01mm，核心客户德国与日本）、陶瓷餐具套装（高温骨瓷，FDA/LFGB 安全认证，核心客户欧洲）、智能家居套件（WiFi/Zigbee 双协议，APP 远程控制，重点拓品）。',
    summary: '核心产品线知识总纲',
    source: '产品部知识库导入',
    confidence: 1.0,
    frozen: true,
    tags: ['产品知识', 'SOP', '核心资产'],
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'mem-010',
    type: 'long',
    content: '外贸报价 SOP：FOB 报价 = 出厂价 + 国内运费 + 港杂；CIF 报价 = FOB + 海运费 + 保险费。常规产品毛利率不低于 25%，大客户阶梯折扣最高 15%。报价有效期 15 天（汇率波动 >2% 时提前失效）。所有报价单需经业务经理审批后方可发出。',
    summary: '外贸报价标准作业流程',
    source: '业务部 SOP 文档',
    relatedAgent: 'agent-004',
    confidence: 1.0,
    frozen: true,
    tags: ['SOP', '报价', '流程', '核心资产'],
    createdAt: '2025-11-01T08:00:00Z',
  },
  {
    id: 'mem-011',
    type: 'long',
    content: '主要目标市场认证要求：美国（UL/ETL 强制，FCC 电磁兼容，FDA 食品接触）、欧洲（CE 强制，RoHS/REACH 环保，LFGB 食品接触，UKCA 英国特定）、日本（PSE 电气安全，JIS 工业标准，食品卫生法）、澳洲（AS/NZS 标准，RCM 电气安全）。认证周期通常 4-12 周，费用 $2K-$50K 不等。',
    summary: '全球主要市场认证要求总表',
    source: '合规部知识库',
    relatedAgent: 'agent-008',
    confidence: 0.99,
    frozen: true,
    tags: ['认证', '合规', '市场准入', '核心资产'],
    createdAt: '2025-12-15T08:00:00Z',
  },
  {
    id: 'mem-012',
    type: 'long',
    content: '历史重大案例——德国 Schmidt 质量危机处置（2025.10）：表面处理色差问题导致两批次退货，损失约 €15K。根本原因：国产表面处理供应商工艺不稳定。解决方案：转用日本指定供应商，增加出货前全检环节，建立色差标准样品库。教训：欧洲高端客户对细节要求远超预期，前期需充分对齐质量标准。',
    summary: 'Schmidt 质量危机案例复盘',
    source: '案例复盘会议纪要',
    relatedProject: 'proj-002',
    relatedAgent: 'agent-008',
    confidence: 1.0,
    frozen: true,
    tags: ['案例', '质量', '复盘', '教训', '核心资产'],
    createdAt: '2025-11-20T08:00:00Z',
  },
]

// ============================================================
// Harness 进化提案（3 条：低/中/高风险各 1 条）
// ============================================================
export const mockHarnessProposals: HarnessProposal[] = [
  {
    id: 'hep-001',
    proposalId: 'HEP-20260601-001',
    triggeredBy: 'auto',
    triggerReason: '假阳性率偏高',
    problemStatement: '询盘分拣员（agent-002）在过去 7 天中共处理 320 条询盘，其中 12 条被标记为虚假询盘但实际为真实客户（假阳性率 3.75%），高于 2% 的阈值。虚假询盘检测模型的置信度阈值需要微调。',
    evidence: [
      '6 月 1 日：尼日利亚客户 Lifemate 被误判为虚假询盘，实际为当地知名连锁',
      '6 月 3 日：印尼客户两次询盘被标记，手动复核确认真实',
      'agent-002 上周假阳性率从 1.8% 升至 3.75%',
    ],
    proposedChange: {
      targetComponent: '任务边界',
      description: '将虚假询盘判定置信度阈值从 0.80 调整为 0.75，同时新增西非与东南亚地区的"白名单域名"规则，对来自企业域名的询盘降低可疑权重',
      riskLevel: 'low',
      automationLevel: 'L1',
    },
    requiresHumanApproval: true,
    affectedAgents: ['agent-002'],
    rollbackPlan: '恢复置信度阈值为 0.80，移除白名单规则',
    status: 'approved',
    estimatedImpact: '预计假阳性率可降至 2% 以下，不影响真阳性检出率；影响约 5% 的低置信度询盘路由路径',
    createdAt: '2026-06-01T08:00:00Z',
    reviewedBy: '张伟',
    reviewedAt: '2026-06-02T10:30:00Z',
  },
  {
    id: 'hep-002',
    proposalId: 'HEP-20260603-002',
    triggeredBy: 'auto',
    triggerReason: '渠道跟进回复率下降',
    problemStatement: '客户跟进员（agent-003）在 Whatsapp 渠道的跟进成功率从 4 月的 68% 下降到 5 月的 51%。分析发现 agent-003 的跟进内容模板未适配即时通讯场景——内容过长、语气过于正式，与 WhatsApp 用户期望的简洁沟通风格不匹配。',
    evidence: [
      'WhatsApp 渠道跟进回复率：4 月 68% → 5 月 51%',
      '5 月客户反馈："信息太长，像邮件不像聊天"',
      '对比测试：短版（<100字）消息回复率 72%，长版（>200字）仅 38%',
      '竞品调研：同行在 WhatsApp 上平均消息长度约 80 字',
    ],
    proposedChange: {
      targetComponent: '上下文供给',
      description: '为 agent-003 新增"渠道感知"能力：自动识别沟通渠道（邮件/WhatsApp/微信），动态调整消息长度与语气风格。同时将中期记忆中沉淀的客户渠道偏好纳入上下文供给链。',
      riskLevel: 'medium',
      automationLevel: 'L2',
    },
    requiresHumanApproval: true,
    affectedAgents: ['agent-003'],
    rollbackPlan: '恢复原版跟进内容模板，关闭"渠道感知"特性',
    status: 'pending',
    estimatedImpact: '预计 WhatsApp 渠道跟进回复率可回升至 65%+，邮件渠道效率不受影响；需 3-5 天开发 + 1 天回归测试',
    createdAt: '2026-06-03T14:00:00Z',
  },
  {
    id: 'hep-003',
    proposalId: 'HEP-20260605-003',
    triggeredBy: 'manual',
    triggerReason: 'API 延迟导致损失风险',
    problemStatement: '报价代理（agent-004）目前使用的汇率数据来源为单一 API（conn-018 XE），近期发现该 API 在亚洲交易时段（UTC+8 上午）存在 5-15 分钟的延迟，导致报价与实际汇率产生偏差。在 6 月 4 日的一次报价中，因汇率延迟导致 CIF 报价比实际成本低了 0.8%，若成交将造成约 $1,200 的汇兑损失。',
    evidence: [
      '6 月 4 日 09:35 报价：XE 汇率 7.1823，实际银行间汇率 7.2410，偏差 0.81%',
      '近 30 天中 8 天存在亚洲早盘延迟 >5 分钟',
      'agent-004 5 月共生成 67 份报价，其中 4 份因汇率偏差需要事后修正',
      '已确认备用数据源：中国银行外汇牌价 API 实时性更优（北京时间）',
    ],
    proposedChange: {
      targetComponent: '工具接入',
      description: '1) 将汇率数据源从单一 XE API 改为双源容灾（XE + 中国银行外汇牌价），增加数据源健康检查；2) 当双源偏差 >0.3% 时自动暂停报价并告警；3) 报价单强制标注汇率基准时间与来源。涉及修改 agent-004 的任务边界（canDo 新增"调用多汇率源交叉验证"）。',
      riskLevel: 'high',
      automationLevel: 'L3',
    },
    requiresHumanApproval: true,
    affectedAgents: ['agent-004'],
    rollbackPlan: '将汇率源切换回单节点 XE API，暂时关闭容灾策略并人工复核报价',
    status: 'pending',
    estimatedImpact: '直接避免汇兑损失，但变更涉及 Agent 任务边界修改（HEP 流程要求）和 connector 注册表更新，需全量回归测试报价生成链路。预计开发 5 天 + 测试 3 天。',
    createdAt: '2026-06-05T11:00:00Z',
  },
]

// ============================================================
// 询盘 Inquiries（10 条，来自不同国家）
// ============================================================
export const mockInquiries: Inquiry[] = [
  {
    id: 'inq-001',
    fromCountry: '美国',
    countryFlag: '🇺🇸',
    companyName: 'BrightPath Outdoors Inc.',
    summary: '询价 IP65 户外 LED 投光灯 200W，数量 500pcs，要求 UL 认证，目标交期 2026 年 8 月',
    priority: 'high',
    channel: 'Alibaba国际站',
    receivedAt: '2026-06-06T09:30:00Z',
    replied: true,
  },
  {
    id: 'inq-002',
    fromCountry: '德国',
    countryFlag: '🇩🇪',
    companyName: 'Schmidt Präzisionstechnik GmbH',
    summary: '精密 CNC 加工铝件，公差要求 ±0.01mm，询批量价格，年需求量约 50,000pcs',
    priority: 'high',
    channel: '邮件',
    receivedAt: '2026-06-06T08:15:00Z',
    replied: true,
  },
  {
    id: 'inq-003',
    fromCountry: '日本',
    countryFlag: '🇯🇵',
    companyName: '株式会社 Sakura Living',
    summary: '家居收纳用品 ODM 询盘，需要打样确认后再确定订单量，关注表面处理工艺',
    priority: 'high',
    channel: '邮件',
    receivedAt: '2026-06-05T15:00:00Z',
    replied: true,
  },
  {
    id: 'inq-004',
    fromCountry: '英国',
    countryFlag: '🇬🇧',
    companyName: 'Hackett Department Stores Ltd.',
    summary: '陶瓷餐具 16 件套，要求 LFGB 食品安全认证，首批试单 2000 套，需 UKCA 标识',
    priority: 'high',
    channel: '邮件',
    receivedAt: '2026-06-05T11:20:00Z',
    replied: true,
  },
  {
    id: 'inq-005',
    fromCountry: '巴西',
    countryFlag: '🇧🇷',
    companyName: 'Verde Vida Comércio Ltda.',
    summary: '太阳能庭院灯，数量 2000-5000pcs，关注巴西 INMETRO 认证和运费成本',
    priority: 'mid',
    channel: 'WhatsApp',
    receivedAt: '2026-06-05T10:00:00Z',
    replied: false,
  },
  {
    id: 'inq-006',
    fromCountry: '法国',
    countryFlag: '🇫🇷',
    companyName: 'Maison Élégance SARL',
    summary: '高端骨瓷茶具套装 OEM，要求定制礼盒包装，关注 FOB 上海报价',
    priority: 'mid',
    channel: '邮件',
    receivedAt: '2026-06-04T16:45:00Z',
    replied: true,
  },
  {
    id: 'inq-007',
    fromCountry: '澳大利亚',
    countryFlag: '🇦🇺',
    companyName: 'Coastal Living Pty Ltd.',
    summary: '户外防水灯串 10m/20m，各 1000pcs，需要 AS/NZS 60598 认证，目标圣诞节上架',
    priority: 'mid',
    channel: 'Alibaba国际站',
    receivedAt: '2026-06-04T14:30:00Z',
    replied: false,
  },
  {
    id: 'inq-008',
    fromCountry: '韩国',
    countryFlag: '🇰🇷',
    companyName: '한국리빙 (Korea Living Co.)',
    summary: '智能家居 WiFi 插座，询价 3000pcs，要求 KC 认证，关注 APP 韩语适配',
    priority: 'mid',
    channel: '邮件',
    receivedAt: '2026-06-04T09:00:00Z',
    replied: true,
  },
  {
    id: 'inq-009',
    fromCountry: '阿联酋',
    countryFlag: '🇦🇪',
    companyName: 'Al-Khaleej Trading Est.',
    summary: 'LED 工矿灯 150W，数量 800pcs，需 SASO 认证，关注中东市场售后支持',
    priority: 'low',
    channel: 'WhatsApp',
    receivedAt: '2026-06-03T13:00:00Z',
    replied: false,
  },
  {
    id: 'inq-010',
    fromCountry: '印尼',
    countryFlag: '🇮🇩',
    companyName: 'PT Cahaya Nusantara',
    summary: '太阳能路灯全套方案，试点项目 200 套，需要当地安装指导和技术培训支持',
    priority: 'low',
    channel: '邮件',
    receivedAt: '2026-06-03T10:30:00Z',
    replied: true,
  },
]

// ============================================================
// 市场情报 Market Intelligence（8 条）
// ============================================================
export const mockIntelligence: MarketIntelligence[] = [
  {
    id: 'intel-001',
    type: 'currency',
    title: '美元兑人民币汇率突破 7.25，创年内新高',
    summary: '6 月 6 日在岸人民币兑美元收报 7.2513，较月初上升 0.8%。美联储 6 月加息预期升温推动美元走强。对出口企业有利，但需关注进口原材料成本上升。',
    source: '中国外汇交易中心',
    credibility: 0.99,
    impactLevel: 'high',
    suggestedAction: '锁定近期美元订单汇率，调整非美货币报价基准，关注欧元/人民币交叉汇率联动',
    publishedAt: '2026-06-06T07:00:00Z',
  },
  {
    id: 'intel-002',
    type: 'tariff',
    title: '欧盟拟对部分中国 LED 产品加征临时反补贴税',
    summary: '欧盟委员会 6 月 5 日启动对中国 LED 照明产品的反补贴调查，涉及功率 50W-300W 的户外灯具，可能加征 15%-25% 的临时关税，调查期预计 6-9 个月。',
    source: '欧盟官方公报',
    credibility: 0.95,
    impactLevel: 'high',
    suggestedAction: '评估受影响产品比例，加速订单出货窗口期，调研东南亚转口可行性，准备应诉材料',
    publishedAt: '2026-06-05T16:00:00Z',
  },
  {
    id: 'intel-003',
    type: 'competitor',
    title: 'Aqara 宣布进入欧洲智能照明市场',
    summary: '小米生态链品牌 Aqara 在 6 月 IFA 预热发布会上宣布将于 Q3 大规模进入欧洲智能照明市场，首批覆盖德法英三国，定价区间 €29-€89，与我们的智能家居产品线直接竞争。',
    source: 'IFA 官方新闻 + Aqara 官网',
    credibility: 0.97,
    impactLevel: 'high',
    suggestedAction: '加速智能照明差异化功能开发（场景联动 + 语音控制），提前锁定核心渠道代理商',
    publishedAt: '2026-06-04T10:00:00Z',
  },
  {
    id: 'intel-004',
    type: 'market',
    title: '全球户外照明市场预计 2026 年增长 12%',
    summary: '据 Grand View Research 6 月报告，全球户外照明市场规模预计 2026 年达 $185 亿，年增长率 12%。主要驱动力：城市亮化工程、智能路灯替换需求、家用庭院灯光消费升级。北美和欧洲占比超 60%。',
    source: 'Grand View Research',
    credibility: 0.91,
    impactLevel: 'mid',
    suggestedAction: '加大户外灯具产品线投入，重点关注北美智能路灯和欧洲庭院装饰灯细分市场',
    publishedAt: '2026-06-03T08:00:00Z',
  },
  {
    id: 'intel-005',
    type: 'logistics',
    title: '上海至汉堡海运即期运价回升至 $2,800/FEU',
    summary: '6 月第一周上海出口集装箱运价指数（SCFI）欧洲线报 $2,800/FEU，环比上升 15%。地中海航运（MSC）宣布 7 月 1 日起加收旺季附加费（PSS）$400/FEU。舱位紧张预计持续至 Q3。',
    source: '上海航运交易所 + MSC 公告',
    credibility: 0.98,
    impactLevel: 'mid',
    suggestedAction: '提前预订 Q3 舱位锁定当前运价，评估中欧班列替代方案成本，更新 CIF 报价中海运费预算',
    publishedAt: '2026-06-05T09:00:00Z',
  },
  {
    id: 'intel-006',
    type: 'market',
    title: '日本家居收纳市场偏好向环保材质快速转型',
    summary: '日本经济产业省 6 月发布《可持续消费趋势报告》，显示 67% 的日本消费者愿为环保材质家居用品支付 15% 以上溢价。竹纤维、再生塑料、可降解材料成为新宠。',
    source: '日本经济产业省报告',
    credibility: 0.93,
    impactLevel: 'mid',
    suggestedAction: '评估 Sakura 项目的材质替代方案，探索竹纤维收纳产品研发可行性，更新日本市场产品策略',
    publishedAt: '2026-06-02T08:00:00Z',
  },
  {
    id: 'intel-007',
    type: 'competitor',
    title: '印度 LED 照明出口增长 35%，挤占中低端市场份额',
    summary: '印度商工部数据显示 2026 年 Q1 LED 照明出口同比增长 35%，主要覆盖中东、非洲和东南亚中低端市场。印度产品价格比中国同类低 15%-20%，但在高端认证产品线上竞争力仍有限。',
    source: '印度商工部 + LEDinside 行业分析',
    credibility: 0.88,
    impactLevel: 'mid',
    suggestedAction: '聚焦中高端认证产品线差异化竞争，关注中东市场份额变化，评估印度供应链合作可能性',
    publishedAt: '2026-06-01T14:00:00Z',
  },
  {
    id: 'intel-008',
    type: 'tariff',
    title: '英国 UKCA 标识强制执行再推迟至 2027 年',
    summary: '英国商业贸易部 6 月 3 日宣布 UKCA 标识强制执行日期再次推迟至 2027 年 1 月 1 日，过渡期内继续接受 CE 标识。此举为出口英国的企业争取了额外缓冲时间。',
    source: '英国商业贸易部公告',
    credibility: 0.99,
    impactLevel: 'low',
    suggestedAction: '利用缓冲期有序推进 UKCA 认证，优先处理高销量 SKU，无需紧急切换标识方案',
    publishedAt: '2026-06-03T12:00:00Z',
  },
]

// ============================================================
// 报价 Quotations（5 条，跨不同项目）
// ============================================================
export const mockQuotations: Quotation[] = [
  {
    id: 'quot-001',
    projectId: 'proj-001',
    version: 3,
    totalAmount: '68,500.00',
    currency: 'USD',
    status: 'draft',
    createdAt: '2026-06-05T16:00:00Z',
  },
  {
    id: 'quot-002',
    projectId: 'proj-002',
    version: 8,
    totalAmount: '45,200.00',
    currency: 'EUR',
    status: 'sent',
    createdAt: '2026-06-04T10:00:00Z',
  },
  {
    id: 'quot-003',
    projectId: 'proj-003',
    version: 2,
    totalAmount: '3,850,000.00',
    currency: 'JPY',
    status: 'draft',
    createdAt: '2026-06-03T14:00:00Z',
  },
  {
    id: 'quot-004',
    projectId: 'proj-006',
    version: 1,
    totalAmount: '32,800.00',
    currency: 'GBP',
    status: 'accepted',
    createdAt: '2026-05-20T09:00:00Z',
  },
  {
    id: 'quot-005',
    projectId: 'proj-008',
    version: 1,
    totalAmount: '156,000.00',
    currency: 'USD',
    status: 'draft',
    createdAt: '2026-06-02T11:00:00Z',
  },
]

// ============================================================
// 汇率 ExchangeRates（外贸页汇率监测卡片种子数据）
// ============================================================
export interface ExchangeRateSeed {
  id: string
  pair: string
  value: number
  change24h: number
}

export const mockExchangeRates: ExchangeRateSeed[] = [
  { id: 'rate-001', pair: 'USD/CNY', value: 7.2431, change24h: -0.08 },
  { id: 'rate-002', pair: 'EUR/CNY', value: 7.8902, change24h: 0.12 },
  { id: 'rate-003', pair: 'GBP/CNY', value: 9.2156, change24h: 0.05 },
  { id: 'rate-004', pair: 'JPY/CNY', value: 0.0478, change24h: -0.23 },
]
