import { withRBAC } from "@/lib/server/api-handler"; import { decideApprovalCheckpoint } from "@/lib/server/approval"; import type { RouteContext } from "@/lib/server/api-handler"

export const POST = withRBAC(async (request: any, ctx: any, routeContext: RouteContext<{ id: string }>) => {
  const { id } = await routeContext.params; const body = await request.json()
  const decision = body.decision || "approved"; const decidedBy = body.decidedBy || ctx.userId || "system"; const comment = body.comment || ""
  if (decision !== "approved" && decision !== "rejected") return Response.json({ success: false, error: "Invalid decision" }, { status: 400 })
  const checkpoint = await decideApprovalCheckpoint(id, decision, decidedBy, comment, {
    writeAuditLog: async (input: any) => { const { writeAuditLog } = await import("@/lib/server/audit"); await writeAuditLog(input) },
    recordProposalSnapshot: async (proposalId: string) => { const { prisma } = await import("@/lib/prisma"); const proposal = await prisma.harnessProposal.findUnique({ where: { id: proposalId }, select: { workspaceId: true, affectedAgents: true } }); if (!proposal) return; const { captureSnapshot } = await import("@/lib/server/harness-snapshot"); let agentIds: string[] = []; try { agentIds = typeof proposal.affectedAgents === "string" ? JSON.parse(proposal.affectedAgents) || [] : Array.isArray(proposal.affectedAgents) ? proposal.affectedAgents : [] } catch {}; for (const agentId of agentIds.length > 0 ? agentIds : ["default"]) await captureSnapshot({ workspaceId: proposal.workspaceId, agentId, proposalId, snapshotType: "pre-canary", createdBy: "system" }) },
    triggerCanary: async (proposalId: string) => { const { prisma } = await import("@/lib/prisma"); const proposal = await prisma.harnessProposal.findUnique({ where: { id: proposalId }, select: { workspaceId: true, affectedAgents: true } }); if (!proposal) return; const { startCanary } = await import("@/lib/server/canary"); const { getLatestSnapshot } = await import("@/lib/server/harness-snapshot"); let agentIds: string[] = []; try { agentIds = typeof proposal.affectedAgents === "string" ? JSON.parse(proposal.affectedAgents) || [] : Array.isArray(proposal.affectedAgents) ? proposal.affectedAgents : [] } catch {}; const targetAgentId = agentIds.length > 0 ? agentIds[0] : "default"; const snapshot = await getLatestSnapshot(proposal.workspaceId, targetAgentId); if (!snapshot) return; await startCanary({ proposalId, workspaceId: proposal.workspaceId, agentId: targetAgentId, snapshotId: snapshot.snapshotId, startedBy: "system" }) },
  })
  return Response.json({ success: true, data: checkpoint })
}, "ADMIN")
